# Generated by Django 4.2.4 on 2024-03-05 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReceiptData', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivo',
            name='nombre',
            field=models.CharField(default='none', max_length=100),
        ),
        migrations.DeleteModel(
            name='Datosnoestructurados',
        ),
    ]
