# Generated by Django 4.2.4 on 2024-03-05 14:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ReceiptData', '0002_archivo_nombre_delete_datosnoestructurados'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivo',
            name='fecha_subida',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='archivo',
            name='archivo',
            field=models.FileField(upload_to=''),
        ),
    ]
